SET IDENTITY_INSERT [dbo].[Image] ON
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (1, 1, N'img/home/gallery/bgw1.png', 1, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (2, 2, N'img/home/gallery/bgw2.png', 1, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (3, 3, N'img/home/gallery/bgw3.png', 1, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (4, 4, N'img/home/gallery/bgw4.png', 1, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (5, 5, N'img/home/gallery/bgw5.png', 1, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (6, 6, N'img/home/gallery/bgm1.png', 1, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (7, 7, N'img/home/gallery/bgm2.png', 1, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (8, 8, N'img/home/gallery/cl1.png', 1, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (9, 9, N'img/home/gallery/cl2.png', 1, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (10, 1, N'img/home/new/bgw1.png', 2, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (11, 2, N'img/home/new/bgw2.png', 2, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (12, 3, N'img/home/new/bgw3.png', 2, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (13, 4, N'img/home/new/bgw4.png', 2, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (14, 6, N'img/home/new/bgm1.png', 2, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (15, 8, N'img/home/new/cl1.png', 2, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (16, 6, N'/img/one/gallery/bgm1', 4, 6)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (23, 7, N'/img/one/gallery/bgm2', 4, 2)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (26, 1, N'/img/one/main/bgw1.png', 3, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (27, 2, N'/img/one/main/bgw2.png', 3, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (28, 3, N'/img/one/main/bgw3.png', 3, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (29, 4, N'/img/one/main/bgw4.png', 3, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (30, 5, N'/img/one/main/bgw5.png', 3, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (31, 6, N'/img/one/main/bgm1.png', 3, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (32, 7, N'/img/one/main/bgm2.png', 3, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (33, 8, N'/img/one/main/cl1.png', 3, NULL)
INSERT INTO [dbo].[Image] ([Id], [ProductId], [Guide], [ImageTypeId], [Quan]) VALUES (34, 9, N'/img/one/main/cl2.png', 3, NULL)
SET IDENTITY_INSERT [dbo].[Image] OFF
